/**
 * Validation Engine Orchestrator
 *
 * Combines design matching + policy checking to produce
 * a final per-rule verdict for each firewall request rule.
 */

import type {
  FirewallRule,
  DesignRow,
  Guideline,
  Verdict,
  ValidationResult,
} from "@/types";
import {
  compareRulesAgainstDesign,
  type DesignMatchResult,
} from "./design-comparator";
import {
  checkAllRules,
  type PolicyCheckResult,
} from "./policy-checker";

export interface EngineResult {
  results: ValidationResult[];
  summary: {
    total: number;
    approved: number;
    rejected: number;
    clarificationNeeded: number;
  };
  designMatches: DesignMatchResult[];
  policyResults: PolicyCheckResult[];
}

/**
 * Decision matrix:
 *   Design match + Policy compliant        → APPROVED
 *   Design match + Policy violation         → CLARIFICATION_NEEDED
 *   No design match + Policy compliant      → CLARIFICATION_NEEDED
 *   No design match + Policy violation      → REJECTED
 */
function combineVerdicts(
  designMatch: DesignMatchResult,
  policyResult: PolicyCheckResult
): { verdict: Verdict; confidence: number; reason: string } {
  const hasDesignMatch = designMatch.verdict === "approved";
  const isCompliant = policyResult.isCompliant;

  const policyReasons = policyResult.violations
    .map((v) => `[${v.cautionId}] ${v.reason}`)
    .join(" | ");

  if (hasDesignMatch && isCompliant) {
    return {
      verdict: "approved",
      confidence: designMatch.confidence,
      reason: `APPROVED: ${designMatch.reason}`,
    };
  }

  if (hasDesignMatch && !isCompliant) {
    return {
      verdict: "clarification_needed",
      confidence: Math.min(designMatch.confidence, 0.7),
      reason: `DESIGN MATCH but POLICY CONCERN: ${designMatch.reason} However, policy violations found: ${policyReasons}`,
    };
  }

  if (!hasDesignMatch && isCompliant) {
    return {
      verdict: "clarification_needed",
      confidence: designMatch.confidence,
      reason: `NO DESIGN MATCH but policy compliant. ${designMatch.reason} Confirm this connection is part of the approved design.`,
    };
  }

  // No design match + policy violation
  return {
    verdict: "rejected",
    confidence: Math.max(designMatch.confidence, 0.6),
    reason: `REJECTED: Not in approved design AND policy violations found. ${designMatch.reason} Policy: ${policyReasons}`,
  };
}

/**
 * Run the full validation engine on a set of firewall rules.
 */
export function runValidation(
  fwRules: FirewallRule[],
  designRows: DesignRow[],
  guidelines: Guideline[],
  validationId: string
): EngineResult {
  // Step 1: Compare each FW rule against approved design
  const designMatches = compareRulesAgainstDesign(fwRules, designRows);

  // Step 2: Check each FW rule against policies
  const policyResults = checkAllRules(fwRules, guidelines);

  // Step 3: Combine verdicts
  const results: ValidationResult[] = fwRules.map((rule, idx) => {
    const designMatch = designMatches[idx];
    const policyResult = policyResults[idx];
    const combined = combineVerdicts(designMatch, policyResult);

    return {
      id: "", // generated by DB
      validationId,
      fwRuleRef: rule.userRef,
      verdict: combined.verdict,
      confidence: combined.confidence,
      matchedDesignRowId: undefined,
      policyViolations: policyResult.violations.map((v) => v.cautionId),
      reason: combined.reason,
      createdAt: new Date().toISOString(),
    };
  });

  // Summary
  const summary = {
    total: results.length,
    approved: results.filter((r) => r.verdict === "approved").length,
    rejected: results.filter((r) => r.verdict === "rejected").length,
    clarificationNeeded: results.filter((r) => r.verdict === "clarification_needed").length,
  };

  return { results, summary, designMatches, policyResults };
}
